export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const PROJECT_CREATE_FAIL = "PROJECT_CREATE_FAIL";
export const PROJECTS_FETCH = "PROJECTS_FETCH";
export const PROJECTS_FETCH_SUCCESS = "PROJECTS_FETCH_SUCCESS";
export const PROJECTS_FETCH_FAIL = "PROJECTS_FETCH_FAIL";
export const PROJECT_UPDATE_SUCCESS = "PROJECT_UPDATE_SUCCESS";
export const PROJECT_UPDATE_FAIL = "PROJECT_UPDATE_FAIL";
export const PROJECTS_FETCHBYID = "PROJECTS_FETCHBYID";
export const PROJECTS_FETCHBYID_SUCCESS = "PROJECTS_FETCHBYID_SUCCESS";
export const PROJECTS_FETCHBYID_FAIL = "PROJECTS_FETCHBYID_FAIL";

export const BOARD_CREATE = "BOARD_CREATE";
export const BOARD_CREATE_SUCCESS = "BOARD_CREATE_SUCCESS";
export const BOARD_CREATE_FAIL = "BOARD_CREATE_FAIL";
export const BOARDS_FETCHBYID = "BOARDS_FETCHBYID";
export const BOARDS_FETCHBYID_SUCCESS = "BOARDS_FETCHBYID_SUCCESS";
export const BOARDS_FETCHBYID_FAIL = "BOARDS_FETCHBYID_FAIL";
export const BOARDS_UPDATEBYID = "BOARDS_UPDATEBYID";
export const BOARDS_UPDATEBYID_SUCCESS = "BOARDS_UPDATEBYID_SUCCESS";
export const BOARDS_UPDATEBYID_FAIL = "BOARDS_UPDATEBYID_FAIL";
export const UPLOADED_IMAGES_FETCH = "UPLOADED_IMAGES_FETCH";
export const UPLOADED_IMAGES_FETCH_SUCCESS = "UPLOADED_IMAGES_FETCH_SUCCESS";
export const UPLOADED_IMAGES_FETCH_FAIL = "UPLOADED_IMAGES_FETCH_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
